/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/intenciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crear Intencion
         * @description Encola una intencion. El worker la recoge; la API no ejecuta nada.
         *
         *     La API valida la FORMA; el estado lo valida el worker, que es quien lo conoce.
         */
        post: operations["crear_intencion_intenciones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intenciones/{intencion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver Intencion */
        get: operations["ver_intencion_intenciones__intencion_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Novelas */
        get: operations["listar_novelas_novelas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{novela_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver Novela */
        get: operations["ver_novela_novelas__novela_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{novela_id}/apariciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver Apariciones */
        get: operations["ver_apariciones_novelas__novela_id__apariciones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{novela_id}/cambios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Cambios */
        get: operations["listar_cambios_novelas__novela_id__cambios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{novela_id}/cambios/alcance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ver Alcance
         * @description La misma regla que usa el worker para decidir que reescribe (RF3-CAM-05).
         */
        get: operations["ver_alcance_novelas__novela_id__cambios_alcance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{novela_id}/cambios/{cambio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver Cambio */
        get: operations["ver_cambio_novelas__novela_id__cambios__cambio_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{novela_id}/canon/{entidad}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver Canon */
        get: operations["ver_canon_novelas__novela_id__canon__entidad__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{novela_id}/capitulos/{numero}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver Capitulo */
        get: operations["ver_capitulo_novelas__novela_id__capitulos__numero__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{novela_id}/capitulos/{numero}/versiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver Versiones */
        get: operations["ver_versiones_novelas__novela_id__capitulos__numero__versiones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{novela_id}/conocimiento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver Conocimiento */
        get: operations["ver_conocimiento_novelas__novela_id__conocimiento_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{novela_id}/cronologia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ver Cronologia
         * @description Los eventos en orden de dia, con su lugar y sus personajes (spec3, RF3-BIB-10).
         */
        get: operations["ver_cronologia_novelas__novela_id__cronologia_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{novela_id}/ejecucion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ver Ejecucion
         * @description El estado completo. Esta es la verdad; el stream solo avisa de que cambio.
         */
        get: operations["ver_ejecucion_novelas__novela_id__ejecucion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{novela_id}/estructura": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver Estructura */
        get: operations["ver_estructura_novelas__novela_id__estructura_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{novela_id}/eventos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Eventos
         * @description SSE. Un evento avisa de que algo cambio; el cliente reconsulta.
         *
         *     Si el cliente trae `Last-Event-ID`, se retoma justo despues. La reconexion es un caso de
         *     primera clase: esto va a estar abierto horas.
         */
        get: operations["stream_eventos_novelas__novela_id__eventos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{novela_id}/hechos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver Hechos */
        get: operations["ver_hechos_novelas__novela_id__hechos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{novela_id}/hechos/{hecho_id}/usos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ver Usos De Hecho
         * @description Donde se establece y donde se usa un hecho (spec3, RF3-BIB-02).
         */
        get: operations["ver_usos_de_hecho_novelas__novela_id__hechos__hecho_id__usos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{novela_id}/paradas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Paradas */
        get: operations["listar_paradas_novelas__novela_id__paradas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{novela_id}/paradas/{parada_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver Parada */
        get: operations["ver_parada_novelas__novela_id__paradas__parada_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{novela_id}/traza/llamadas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ver Llamadas
         * @description Por defecto sin el prompt: son decenas de miles de tokens por fila.
         */
        get: operations["ver_llamadas_novelas__novela_id__traza_llamadas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{novela_id}/versiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Versiones
         * @description Lo que ha leido el lector, version a version (spec3, RF3-BIB-11).
         */
        get: operations["listar_versiones_novelas__novela_id__versiones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{novela_id}/versiones/{numero}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver Version */
        get: operations["ver_version_novelas__novela_id__versiones__numero__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Acto */
        Acto: {
            /** Funcion Narrativa */
            funcion_narrativa?: string | null;
            /** Numero */
            numero: number;
        };
        /**
         * Alcance
         * @description Los capitulos que reescribiria un cambio (spec3, RF3-CAM-05).
         */
        Alcance: {
            /** Capitulos */
            capitulos: number[];
        };
        /** AmenazaCanon */
        AmenazaCanon: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entidad: "amenaza";
            /** Id */
            id: number;
            /** Naturaleza */
            naturaleza: string;
            /** Origen */
            origen?: string | null;
            /** Reglas */
            reglas?: components["schemas"]["ReglaAmenaza"][];
            /** Tema Id */
            tema_id?: number | null;
        };
        /** Aparicion */
        Aparicion: {
            /** Capitulos */
            capitulos: number[];
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
        };
        /**
         * Apariciones
         * @description Donde aparece cada personaje y cada lugar, para la ficha (spec3, RF3-LEC-02).
         */
        Apariciones: {
            /** Lugares */
            lugares: components["schemas"]["Aparicion"][];
            /** Personajes */
            personajes: components["schemas"]["Aparicion"][];
        };
        /**
         * CambioVista
         * @description Un cambio del lector y lo que se hizo con el (spec3, RF3-CAM-13).
         */
        CambioVista: {
            /** Alertas */
            alertas?: string[];
            /** Cambio */
            cambio?: {
                [key: string]: unknown;
            } | null;
            /** Capitulos */
            capitulos?: number[];
            /** Cita */
            cita?: {
                [key: string]: unknown;
            } | null;
            /** Creado En */
            creado_en: string;
            /** Estado */
            estado: string;
            /** Id */
            id: number;
            /** Informe */
            informe?: {
                [key: string]: unknown;
            } | null;
            /** Objetivo */
            objetivo: {
                [key: string]: unknown;
            };
            /** Peticion */
            peticion: string;
            /** Version */
            version?: number | null;
        };
        /** Capitulo */
        Capitulo: {
            /** Escenas */
            escenas?: components["schemas"]["Escena"][];
            /** Estado */
            estado: string;
            /** Numero */
            numero: number;
            /** Objetivo */
            objetivo?: string | null;
            /** Resumen */
            resumen?: string | null;
        };
        /** CapituloTexto */
        CapituloTexto: {
            /** Numero */
            numero: number;
            /** Palabras */
            palabras: number;
            /** Texto */
            texto: string;
            /** Version */
            version: number;
        };
        /** CapituloVersion */
        CapituloVersion: {
            /** Cambiado */
            cambiado: boolean;
            /** Numero */
            numero: number;
            /** Palabras */
            palabras: number;
            /** Texto */
            texto: string;
        };
        /** ConocimientoVista */
        ConocimientoVista: {
            /** Atributo */
            atributo: string;
            /** Capitulo */
            capitulo: number;
            /** Personaje */
            personaje: string;
            /** Postura */
            postura: string;
            /** Sujeto Nombre */
            sujeto_nombre?: string | null;
            /** Valor */
            valor: string;
            /** Via */
            via: string;
        };
        /**
         * Ejecucion
         * @description La verdad sobre la generacion. El frontend pinta esto, no los eventos.
         */
        Ejecucion: {
            /** Actualizado En */
            actualizado_en: string;
            /** Capitulo Actual */
            capitulo_actual?: number | null;
            /**
             * Capitulos Completados
             * @default 0
             */
            capitulos_completados: number;
            /** Estado */
            estado: string;
            /** Fase */
            fase?: string | null;
            /**
             * Intento Actual
             * @default 1
             */
            intento_actual: number;
            /** Novela Id */
            novela_id: number;
            /** Parada Abierta Id */
            parada_abierta_id?: number | null;
            /**
             * Total Capitulos
             * @default 0
             */
            total_capitulos: number;
            /** Ultimo Error */
            ultimo_error?: string | null;
        };
        /** Escena */
        Escena: {
            /**
             * Analepsis
             * @default false
             */
            analepsis: boolean;
            /** Conflicto */
            conflicto: string;
            /** Lugar */
            lugar: string;
            /** Objetivo */
            objetivo: string;
            /** Orden */
            orden: number;
            /** Pov */
            pov: string;
            /** Reparto */
            reparto: string[];
            /** Tension */
            tension?: number | null;
            /** Valor Final */
            valor_final: string;
            /** Valor Inicial */
            valor_inicial: string;
        };
        /** EstadoIntencion */
        EstadoIntencion: {
            /** Creado En */
            creado_en: string;
            /** Estado */
            estado: string;
            /** Id */
            id: number;
            /** Motivo */
            motivo?: string | null;
            /** Resultado */
            resultado?: {
                [key: string]: unknown;
            } | null;
            /** Tipo */
            tipo: string;
        };
        /** EstiloNarrativo */
        EstiloNarrativo: {
            /** Convenciones Formato */
            convenciones_formato?: string | null;
            /** Densidad Sensorial */
            densidad_sensorial: string;
            /** Distancia Psiquica */
            distancia_psiquica: string;
            /** Registro */
            registro: string;
            /** Ritmo Prosa */
            ritmo_prosa: string;
            /** Tics Prohibidos */
            tics_prohibidos?: string[];
        };
        /** Estructura */
        Estructura: {
            /** Actos */
            actos: components["schemas"]["Acto"][];
            /** Capitulos */
            capitulos: components["schemas"]["Capitulo"][];
            /** Hilos */
            hilos: components["schemas"]["Hilo"][];
            /** Puntos De Giro */
            puntos_de_giro: components["schemas"]["PuntoDeGiro"][];
            /** Siembras */
            siembras: components["schemas"]["SiembraVista"][];
        };
        /** EventoCanon */
        EventoCanon: {
            /** Descripcion */
            descripcion: string;
            /** Dia */
            dia?: number | null;
            /** Dramatizado */
            dramatizado: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entidad: "eventos";
            /** Escena Id */
            escena_id?: number | null;
            /** Fecha Interna */
            fecha_interna: string;
            /** Id */
            id: number;
            /** Orden Interno */
            orden_interno?: number | null;
            /** Tipo */
            tipo?: string | null;
        };
        /**
         * EventoCronologia
         * @description Un evento de la cronologia (spec3, RF3-BIB-10). Sin escena, es un antecedente.
         */
        EventoCronologia: {
            /** Capitulo */
            capitulo?: number | null;
            /** Descripcion */
            descripcion: string;
            /** Dia */
            dia?: number | null;
            /** Dramatizado */
            dramatizado: boolean;
            /** Escena Orden */
            escena_orden?: number | null;
            /** Evento Id */
            evento_id: number;
            /** Fecha Interna */
            fecha_interna: string;
            /** Lugar */
            lugar?: string | null;
            /** Orden Interno */
            orden_interno?: number | null;
            /** Personajes */
            personajes?: string[];
            /** Tipo */
            tipo?: string | null;
        };
        /** FaccionCanon */
        FaccionCanon: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entidad: "facciones";
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Objetivos */
            objetivos?: string | null;
            /** Proposito */
            proposito?: string | null;
            /** Recursos */
            recursos?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Hecho */
        Hecho: {
            /** Atributo */
            atributo: string;
            /** Capitulo Origen */
            capitulo_origen?: number | null;
            /** Categoria */
            categoria: string;
            /** Id */
            id: number;
            /** Sujeto Nombre */
            sujeto_nombre?: string | null;
            /** Sujeto Tipo */
            sujeto_tipo: string;
            /** Valor */
            valor: string;
            /**
             * Vigente
             * @default true
             */
            vigente: boolean;
        };
        /** Hilo */
        Hilo: {
            /** Conflicto Central */
            conflicto_central: string;
            /** Estado */
            estado: string;
            /** Hilo Id */
            hilo_id: number;
            /** Tipo */
            tipo: string;
        };
        /** IntencionEncolada */
        IntencionEncolada: {
            /** Estado */
            estado: string;
            /** Id */
            id: number;
            /** Tipo */
            tipo: string;
        };
        /** Llamada */
        Llamada: {
            /** Agente */
            agente: string;
            /** Capitulo */
            capitulo?: number | null;
            /** Creado En */
            creado_en: string;
            /** Duracion Ms */
            duracion_ms?: number | null;
            /** Entrada */
            entrada?: string | null;
            /** Estado */
            estado: string;
            /** Exit Code */
            exit_code?: number | null;
            /** Id */
            id: number;
            /** Intento */
            intento?: number | null;
            /** Metadatos */
            metadatos?: {
                [key: string]: unknown;
            } | null;
            /** Salida Cruda */
            salida_cruda?: string | null;
            /** Sistema */
            sistema?: string | null;
            /** Tokens Entrada */
            tokens_entrada?: number | null;
            /** Tokens Entrada Por Bloque */
            tokens_entrada_por_bloque?: {
                [key: string]: number;
            } | null;
            /** Tokens Salida */
            tokens_salida?: number | null;
        };
        /** LugarCanon */
        LugarCanon: {
            /** Descripcion */
            descripcion?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entidad: "lugares";
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Sistemas Criticos */
            sistemas_criticos?: number[];
            /** Tipo */
            tipo?: string | null;
        };
        /** MotivoCanon */
        MotivoCanon: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entidad: "motivos";
            /** Id */
            id: number;
            /** Significado Final */
            significado_final?: string | null;
            /** Significado Inicial */
            significado_inicial?: string | null;
            /** Simbolo */
            simbolo: string;
            /** Tema Id */
            tema_id?: number | null;
        };
        /** MundoCanon */
        MundoCanon: {
            /** Culturas */
            culturas?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entidad: "mundo";
            /** Geografia */
            geografia?: string | null;
            /** Historia */
            historia?: string | null;
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Reglas Fisicas */
            reglas_fisicas?: string | null;
        };
        /** NovelaCanon */
        NovelaCanon: {
            /** Creado En */
            creado_en: string;
            /** Genero */
            genero: string;
            /** Id */
            id: number;
            /** Logline */
            logline?: string | null;
            /** Longitud Objetivo */
            longitud_objetivo?: number | null;
            /** Pov Por Defecto */
            pov_por_defecto?: string | null;
            /** Pregunta Dramatica */
            pregunta_dramatica?: string | null;
            /** Premisa */
            premisa?: string | null;
            /** Semilla Premisa */
            semilla_premisa?: string | null;
            /** Subgenero Dominante */
            subgenero_dominante?: string | null;
            /** Tema Central */
            tema_central?: string | null;
            /** Tiempo Verbal */
            tiempo_verbal?: string | null;
            /** Tipo Final */
            tipo_final?: string | null;
            /** Titulo */
            titulo: string;
        };
        /** NovelaDetalle */
        NovelaDetalle: {
            /** Dedicatoria */
            dedicatoria?: string | null;
            estilo?: components["schemas"]["EstiloNarrativo"] | null;
            novela: components["schemas"]["NovelaCanon"];
            regalo?: components["schemas"]["Regalo"] | null;
            /** Restricciones */
            restricciones: {
                [key: string]: string;
            };
        };
        /** NovelaResumen */
        NovelaResumen: {
            /**
             * Capitulos Completados
             * @default 0
             */
            capitulos_completados: number;
            /** Creado En */
            creado_en: string;
            /** Estado */
            estado?: string | null;
            /** Genero */
            genero: string;
            /** Id */
            id: number;
            /** Subgenero Dominante */
            subgenero_dominante?: string | null;
            /** Titulo */
            titulo: string;
        };
        /** NuevaIntencion */
        NuevaIntencion: {
            /** Novela Id */
            novela_id?: number | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "crear_novela" | "arrancar" | "parar" | "relanzar" | "resolver_parada" | "cambio_lector";
        };
        /** ObjetoCanon */
        ObjetoCanon: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entidad: "objetos";
            /** Funcion Narrativa */
            funcion_narrativa?: string | null;
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
        };
        /** Pagina[Hecho] */
        Pagina_Hecho_: {
            /** Items */
            items: components["schemas"]["Hecho"][];
            /** Total */
            total: number;
        };
        /** Parada */
        Parada: {
            /** Capitulo */
            capitulo?: number | null;
            /** Creado En */
            creado_en: string;
            /** Estado */
            estado: string;
            /** Id */
            id: number;
            /** Informe */
            informe?: {
                [key: string]: unknown;
            } | null;
            /** Intento */
            intento?: number | null;
            /** Resolucion */
            resolucion?: string | null;
            /** Tipo */
            tipo: string;
        };
        /** PersonajeCanon */
        PersonajeCanon: {
            /** Defecto */
            defecto?: string | null;
            /** Deseo */
            deseo?: string | null;
            /** Edad */
            edad?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entidad: "personajes";
            /** Faccion Id */
            faccion_id?: number | null;
            /** Fantasma */
            fantasma?: string | null;
            /** Herida */
            herida?: string | null;
            /** Id */
            id: number;
            /** Idiolecto */
            idiolecto?: string | null;
            /** Mentira */
            mentira?: string | null;
            /** Necesidad Interna */
            necesidad_interna?: string | null;
            /** Nombre */
            nombre: string;
            /** Posicion Tematica */
            posicion_tematica?: string | null;
            /** Rol */
            rol?: string | null;
            /** Rol Narrativo */
            rol_narrativo: string;
            /** Secreto */
            secreto?: string | null;
            /** Subtipo Arco */
            subtipo_arco?: string | null;
            /** Tipo Arco */
            tipo_arco?: string | null;
        };
        /** PuntoDeGiro */
        PuntoDeGiro: {
            /** Hilo Id */
            hilo_id: number;
            /** Id */
            id: number;
            /** Posicion */
            posicion: number;
            /** Tipo */
            tipo: string;
        };
        /**
         * Regalo
         * @description Para la portada: para quien, de quien y la ocasion legible (spec3, RF3-LEC-01).
         */
        Regalo: {
            /** De */
            de?: string | null;
            /** Ocasion */
            ocasion?: string | null;
            /** Para */
            para: string;
        };
        /** ReglaAmenaza */
        ReglaAmenaza: {
            /**
             * Activacion
             * @default
             */
            activacion: string;
            /**
             * Capacidad
             * @default
             */
            capacidad: string;
            /**
             * Limite
             * @default
             */
            limite: string;
        };
        /** SiembraVista */
        SiembraVista: {
            /** Capitulo Pago Previsto */
            capitulo_pago_previsto?: number | null;
            /** Elemento */
            elemento: string;
            /** Estado */
            estado: string;
            /** Hilo Id */
            hilo_id?: number | null;
            /** Siembra Id */
            siembra_id: number;
        };
        /** SistemaCanon */
        SistemaCanon: {
            /** Acceso */
            acceso?: string | null;
            /** Capacidades */
            capacidades: string;
            /** Costes */
            costes: string;
            /** Dureza */
            dureza: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entidad: "sistemas";
            /** Id */
            id: number;
            /** Limites */
            limites: string;
            /** Nombre */
            nombre: string;
        };
        /** TemaCanon */
        TemaCanon: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entidad: "temas";
            /** Id */
            id: number;
            /** Pregunta Central */
            pregunta_central: string;
            /** Verdad Tematica */
            verdad_tematica: string;
        };
        /**
         * UsoHecho
         * @description Una escena que establece o usa un hecho (spec3, RF3-BIB-02).
         */
        UsoHecho: {
            /** Capitulo */
            capitulo: number;
            /** Cita */
            cita?: string | null;
            /** Escena Orden */
            escena_orden: number;
            /**
             * Via
             * @enum {string}
             */
            via: "establece" | "reafirma" | "menciona" | "conoce" | "usa";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionEscena */
        VersionEscena: {
            /** Creado En */
            creado_en: string;
            /** Escena */
            escena: number;
            /** Estado */
            estado: string;
            /** Intento */
            intento?: number | null;
            /** Llamada Modelo Id */
            llamada_modelo_id?: number | null;
            /** Origen */
            origen: string;
            /** Palabras */
            palabras: number;
            /** Version */
            version: number;
        };
        /** VersionNovela */
        VersionNovela: {
            /** Capitulos */
            capitulos: components["schemas"]["CapituloVersion"][];
            /** Capitulos Cambiados */
            capitulos_cambiados: number[];
            /** Creado En */
            creado_en: string;
            /** Dedicatoria */
            dedicatoria?: string | null;
            /** Detalle */
            detalle?: string | null;
            /** Motivo */
            motivo: string;
            /** Numero */
            numero: number;
            /** Titulo */
            titulo: string;
        };
        /**
         * VersionResumen
         * @description Una version publicada de la novela (spec3, RF3-BIB-11).
         */
        VersionResumen: {
            /** Capitulos Cambiados */
            capitulos_cambiados: number[];
            /** Creado En */
            creado_en: string;
            /** Dedicatoria */
            dedicatoria?: string | null;
            /** Detalle */
            detalle?: string | null;
            /** Motivo */
            motivo: string;
            /** Numero */
            numero: number;
            /** Titulo */
            titulo: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    crear_intencion_intenciones_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NuevaIntencion"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntencionEncolada"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ver_intencion_intenciones__intencion_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intencion_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstadoIntencion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_novelas_novelas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NovelaResumen"][];
                };
            };
        };
    };
    ver_novela_novelas__novela_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novela_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NovelaDetalle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ver_apariciones_novelas__novela_id__apariciones_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novela_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Apariciones"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_cambios_novelas__novela_id__cambios_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novela_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CambioVista"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ver_alcance_novelas__novela_id__cambios_alcance_get: {
        parameters: {
            query?: {
                entidad?: ("personajes" | "lugares" | "objetos") | null;
                id?: number | null;
                hecho_id?: number | null;
            };
            header?: never;
            path: {
                novela_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alcance"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ver_cambio_novelas__novela_id__cambios__cambio_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novela_id: number;
                cambio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CambioVista"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ver_canon_novelas__novela_id__canon__entidad__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novela_id: number;
                entidad: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["MundoCanon"] | components["schemas"]["SistemaCanon"] | components["schemas"]["LugarCanon"] | components["schemas"]["PersonajeCanon"] | components["schemas"]["FaccionCanon"] | components["schemas"]["AmenazaCanon"] | components["schemas"]["ObjetoCanon"] | components["schemas"]["TemaCanon"] | components["schemas"]["MotivoCanon"] | components["schemas"]["EventoCanon"])[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ver_capitulo_novelas__novela_id__capitulos__numero__get: {
        parameters: {
            query?: {
                version?: number | null;
            };
            header?: never;
            path: {
                novela_id: number;
                numero: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapituloTexto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ver_versiones_novelas__novela_id__capitulos__numero__versiones_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novela_id: number;
                numero: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionEscena"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ver_conocimiento_novelas__novela_id__conocimiento_get: {
        parameters: {
            query?: {
                personaje?: string | null;
                limite?: number;
            };
            header?: never;
            path: {
                novela_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConocimientoVista"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ver_cronologia_novelas__novela_id__cronologia_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novela_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventoCronologia"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ver_ejecucion_novelas__novela_id__ejecucion_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novela_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ejecucion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ver_estructura_novelas__novela_id__estructura_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novela_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Estructura"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_eventos_novelas__novela_id__eventos_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novela_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Un evento de traza por linea `data:`, con su `id:`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ver_hechos_novelas__novela_id__hechos_get: {
        parameters: {
            query?: {
                sujeto?: string | null;
                categoria?: string | null;
                capitulo?: number | null;
                limite?: number;
                desde?: number;
            };
            header?: never;
            path: {
                novela_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_Hecho_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ver_usos_de_hecho_novelas__novela_id__hechos__hecho_id__usos_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novela_id: number;
                hecho_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsoHecho"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_paradas_novelas__novela_id__paradas_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novela_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Parada"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ver_parada_novelas__novela_id__paradas__parada_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novela_id: number;
                parada_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Parada"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ver_llamadas_novelas__novela_id__traza_llamadas_get: {
        parameters: {
            query?: {
                completo?: boolean;
                limite?: number;
            };
            header?: never;
            path: {
                novela_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Llamada"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_versiones_novelas__novela_id__versiones_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novela_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResumen"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ver_version_novelas__novela_id__versiones__numero__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novela_id: number;
                numero: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionNovela"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
